# Generated by Django 4.2.20 on 2025-04-10 05:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0002_alter_cleanertest_graph_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanertest',
            name='test_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
