# Generated by Django 4.2.20 on 2025-04-11 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleaner', '0003_alter_cleanertest_test_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanerTestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_passed_count', models.IntegerField()),
                ('test_failed_count', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('function_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cleaner.cleanertest')),
                ('run_as_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'test run event',
                'verbose_name_plural': 'test run events',
                'db_table': 'cleaner_test_events',
                'managed': True,
            },
        ),
    ]
