# Generated by Django 4.2.20 on 2025-04-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0004_cleanertestevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanertestresult',
            name='test_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='cleaner.cleanertestevent'),
        ),
    ]
